spring:
  application:
    name: statement-processor-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}/personal_finance_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: statement_processor_db
#    generate-ddl: true
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: statement_processor_db.batch_
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      group-id: processor-group